version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: onghub
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  mailcatcher:
    restart: on-failure:10
    image: dockage/mailcatcher:0.9.0
    ports:
      - '1080:1080'
      - '1025:1025'
